<script setup lang="ts">
import { useI18n } from "vue-i18n";
import { ref } from "vue";
import MainHeader from "@/components/MainHeader.vue";
import SubHeader from "@/components/SubHeader.vue";
import LinkItem from "@/components/LinkItem.vue";
import BottomToTopSlideTransition from "@/components/BottomToTopSlideTransition.vue";

const { t } = useI18n();

const privacyPolicy = ref([
  {
    title: t("Introduction"),
    content: [
      t(
        "This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use the Service and tells you about your privacy rights and how the law protects you.",
      ),
      t(
        "We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.",
      ),
    ],
  },
  {
    title: t("Interpretation and Definitions"),
    content: [
      t(
        "The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
      ),
    ],
    definitions: [
      {
        term: t("Company"),
        description: t(
          '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) Make IT Logical, registered as Łukasz Ziaja, al. Wiśniowa 36a/304 53-137 Wrocław, Poland',
        ),
      },
      { term: t("Country"), description: t("Poland") },
      {
        term: t("Service"),
        description: t("The Website https://makeitlogical.io"),
      },
      {
        term: t("Data"),
        description: t(
          "Information that is collected automatically or provided by you when using our Service",
        ),
      },
      {
        term: t("Usage Data"),
        description: t(
          "Data collected automatically, generated by the use of the Service or from the Service infrastructure itself",
        ),
      },
    ],
  },
  {
    title: t("Collecting and Using Your Data"),
    content: [
      t(
        "While using our Service, we may ask you to provide us with certain information that can be used to contact or identify you. We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device.",
      ),
    ],
  },
  {
    title: t("Use of Your Data"),
    content: [
      t("The Company may use the collected data for various purposes:"),
    ],
    list: [
      t("To provide and maintain our Service"),
      t("To notify you about changes to our Service"),
      t(
        "To allow you to participate in interactive features of our Service when you choose to do so",
      ),
      t("To provide customer support"),
      t(
        "To gather analysis or valuable information so that we can improve our Service",
      ),
      t("To monitor the usage of our Service"),
      t("To detect, prevent and address technical issues"),
    ],
  },
  {
    title: t("Retention of Your Personal Data"),
    content: [
      t(
        "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.",
      ),
    ],
  },
  {
    title: t("Transfer of Your Personal Data"),
    content: [
      t(
        "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
      ),
    ],
  },
  {
    title: t("Delete Your Personal Data"),
    content: [
      t(
        "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.",
      ),
    ],
  },
  {
    title: t("Disclosure of Your Personal Data"),
    content: [
      t(
        "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
      ),
    ],
    list: [
      t("Comply with a legal obligation"),
      t("Protect and defend the rights or property of the Company"),
      t(
        "Prevent or investigate possible wrongdoing in connection with the Service",
      ),
      t("Protect the personal safety of Users of the Service or the public"),
      t("Protect against legal liability"),
    ],
  },
  {
    title: t("Security of Your Personal Data"),
    content: [
      t(
        "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
      ),
    ],
  },
  {
    title: t("Use of Cookies and Tracking Technologies"),
    content: [
      t(
        "We use cookies and similar tracking technologies to track the activity on Our Service and store certain information. This information may be used to improve and analyze our Service.",
      ),
      t("The technologies we use may include:"),
    ],
    list: [
      t("Cookies or Browser Cookies"),
      t("Web Beacons"),
      t("Analytics tools"),
    ],
  },
  {
    title: t("Third-Party Analytics"),
    content: [
      t(
        "We may use third-party Service Providers to monitor and analyze the use of our Service. These third-party vendors may have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.",
      ),
    ],
  },
  {
    title: t("Changes to this Privacy Policy"),
    content: [
      t(
        "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
      ),
    ],
  },
]);
</script>

<template>
  <section id="privacy-policy">
    <MainHeader text="Privacy Policy" />
    <SubHeader
      first="We value your privacy and are committed to protecting your data."
      second="This policy outlines how we collect, use, and safeguard your information."
    />
    <BottomToTopSlideTransition>
      <div class="flex flex-col gap-6 max-w-4xl">
        <div v-for="(section, index) in privacyPolicy" :key="index">
          <div class="mb-6">
            <h2 class="text-xl font-bold mb-2">{{ section.title }}</h2>
            <p
              v-for="(paragraph, pIndex) in section.content"
              :key="pIndex"
              class="mb-2"
            >
              {{ paragraph }}
            </p>
            <ul v-if="section.list" class="list-disc pl-5 mb-4">
              <li v-for="(item, iIndex) in section.list" :key="iIndex">
                {{ item }}
              </li>
            </ul>
            <div v-if="section.definitions" class="space-y-4">
              <div
                v-for="(def, dIndex) in section.definitions"
                :key="dIndex"
                class="mb-2"
              >
                <strong>{{ def.term }}:</strong> {{ def.description }}
              </div>
            </div>
          </div>
        </div>
        <div class="flex flex-col gap-2">
          <h2 class="text-xl font-bold mb-2">{{ t("Contact Us") }}</h2>
          <p>
            {{
              t(
                "If you have any questions about this Privacy Policy, you can contact us:",
              )
            }}
          </p>
          <ul class="list-disc pl-5 mb-2 space-y-4 mt-4">
            <li>
              {{ t("By email:") }}
              <LinkItem
                class="mt-2"
                :disable-icon="true"
                :external="true"
                to="mailto:office@makeitlogical.io"
                text="office@makeitlogical.io"
              />
            </li>
            <li>
              {{ t("By phone:") }}
              <LinkItem
                class="mt-2"
                :disable-icon="true"
                :external="true"
                to="tel:+48696606391"
                text="+48 696 606 391"
              />
            </li>
          </ul>
        </div>
      </div>
    </BottomToTopSlideTransition>
  </section>
</template>
