<script setup lang="ts">
import { useI18n } from "vue-i18n";
import { ref } from "vue";
import MainHeader from "@/components/MainHeader.vue";
import SubHeader from "@/components/SubHeader.vue";
import BottomToTopSlideTransition from "@/components/BottomToTopSlideTransition.vue";
import LinkItem from "@/components/LinkItem.vue";

const { t } = useI18n();

const privacyPolicy = ref([
  {
    title: t("Introduction"),
    content: [
      t(
        "This Privacy Policy describes Make IT Logical's policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
      ),
      t(
        "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.",
      ),
    ],
  },
  {
    title: t("Interpretation and Definitions"),
    content: [
      t(
        "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
      ),
    ],
    list: [
      t("Company: Make IT Logical"),
      t("Country: Poland"),
      t("Service: The Website https://makeitlogical.io"),
      t(
        "Personal Data: Any information that relates to an identified or identifiable individual.",
      ),
      t(
        "Usage Data: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
      ),
    ],
  },
  {
    title: t("Collecting and Using Your Personal Data"),
    content: [
      t(
        "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include Usage Data.",
      ),
    ],
  },
  {
    title: t("Use of Your Personal Data"),
    content: [
      t("Make IT Logical may use Personal Data for the following purposes:"),
    ],
    list: [
      t("To provide and maintain our Service"),
      t("To manage Your Account"),
      t("To contact You"),
      t("To manage Your requests"),
      t("For business transfers"),
      t("For other purposes such as data analysis and improving our Service"),
    ],
  },
  {
    title: t("Retention of Your Personal Data"),
    content: [
      t(
        "Make IT Logical will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.",
      ),
    ],
  },
  {
    title: t("Transfer of Your Personal Data"),
    content: [
      t(
        "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
      ),
    ],
  },
  {
    title: t("Delete Your Personal Data"),
    content: [
      t(
        "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service.",
      ),
    ],
  },
  {
    title: t("Disclosure of Your Personal Data"),
    content: [
      t(
        "Make IT Logical may disclose Your Personal Data in the good faith belief that such action is necessary to:",
      ),
    ],
    list: [
      t("Comply with a legal obligation"),
      t("Protect and defend the rights or property of the Company"),
      t(
        "Prevent or investigate possible wrongdoing in connection with the Service",
      ),
      t("Protect the personal safety of Users of the Service or the public"),
      t("Protect against legal liability"),
    ],
  },
  {
    title: t("Security of Your Personal Data"),
    content: [
      t(
        "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
      ),
    ],
  },
  {
    title: t("Changes to this Privacy Policy"),
    content: [
      t(
        "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
      ),
    ],
  },
]);
</script>

<template>
  <section id="privacy-policy">
    <MainHeader>
      {{ t("Privacy Policy") }}
    </MainHeader>
    <SubHeader>
      {{
        t(
          "We value your privacy and are committed to protecting your personal data.",
        )
      }}
      <template #second>
        {{
          t(
            "This policy outlines how we collect, use, and safeguard your information.",
          )
        }}
      </template>
    </SubHeader>
    <BottomToTopSlideTransition duration="1300">
      <div class="flex flex-col gap-4 max-w-4xl">
        <BottomToTopSlideTransition>
          <div
            v-for="(section, index) in privacyPolicy"
            :key="index"
            class="mb-6"
          >
            <h2 class="text-xl font-bold mb-2">{{ section.title }}</h2>
            <p
              v-for="(paragraph, pIndex) in section.content"
              :key="pIndex"
              class="mb-2"
            >
              {{ paragraph }}
            </p>
            <ul v-if="section.list" class="list-disc pl-5 mb-2">
              <li v-for="(item, iIndex) in section.list" :key="iIndex">
                {{ item }}
              </li>
            </ul>
          </div>
        </BottomToTopSlideTransition>
        <BottomToTopSlideTransition>
          <div class="flex flex-col gap-2">
            <h2 class="text-xl font-bold mb-2">{{ t("Contact Us") }}</h2>
            <p>
              {{
                t(
                  "If you have any questions about this Privacy Policy, You can contact us:",
                )
              }}
            </p>
            <ul class="list-disc pl-5 mb-2 space-y-4">
              <li>
                {{ t("By email:") }}
                <LinkItem
                  :disable-icon="true"
                  :external="true"
                  to="mailto:office@makeitlogical.io"
                >
                  office@makeitlogical.io
                </LinkItem>
              </li>
              <li>
                {{ t("By phone:") }}
                <LinkItem
                  :disable-icon="true"
                  :external="true"
                  to="tel:+48696606391"
                >
                  +48 696 606 391
                </LinkItem>
              </li>
            </ul>
          </div>
        </BottomToTopSlideTransition>
      </div>
    </BottomToTopSlideTransition>
  </section>
</template>
